#!/bin/bash

rundir=$(dirname $0)
rskpdpidfile=/tmp/rsk_pd_pid
rskonlinefile=/tmp/rsk_online

function stop_rsk {
  rskpdpid=0
  if [ -f $rskpdpidfile ]
  then 
    rskpdpid=$(cat $rskpdpidfile)
  fi
  while kill $rskpdpid 2> /dev/null
  do
    sleep 2
  done
  return 0
}

function start_rsk {
  cd $rundir
  DISPLAY=:6 \
    pd -noprefs -noaudio -nomidi -nrt \
    -open RSK.pd \
    > /dev/null 2>&1 &
    echo $! > $rskpdpidfile
  return 0
}

function restart_rsk {
  stop_rsk && start_rsk && return 0 || return 1
}

function shutdown_rsk {
  echo "Shutting down RadioSolarKompass..."
  stop_rsk
  exitstop=$?
  echo "Done."
  exit $exitstop
}

trap shutdown_rsk SIGINT

while true
do
  restart_rsk
  while true
  do
    sleep 2
    age=$(($(date +%s) - $(stat -c %Y $rskonlinefile)))
    if [ $age -gt 7 ]
    then
      break
    fi
  done
done
